name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

env:
  REGISTRY: quay.io
  IMAGE: quay.io/tinkerbellrpardini/hegel

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # This step generates the source image name and should coincide with the build from the
      # ci.yaml workflow.
      - name: Generate source image name
        id: src
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGE }}
          flavor: latest=false
          tags: type=sha

      - name: Generate image release tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGE }}
          flavor: latest=false
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: ${{ steps.src.outputs.tags }}
          dst: |
            ${{ steps.meta.outputs.tags }}

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          draft: true
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          body: |
            ## Image

            ```
            docker pull quay.io/tinkerbell/hegel:${{ github.ref_name }}
            ````
